# Generated by Django 3.1 on 2020-08-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
